#!/bin/bash
#--------------------------------------------------------------------
# Run this script after your first boot with archlinux (Anywhere)
#--------------------------------------------------------------------

## BEGIN ~ Collecting information
    clear && echo -e "Arch Gnome ~ Install and set up some packages\n\n" 
    user_name=$(whoami) && echo "User name: $user_name"
    read -p "Seconds to grub [0]: " grub_sec

    if   [ "$grub_sec" == "" ]; then
        grub_sec="0"
    fi
## END

## BEGIN ~ First Packages
    sudo pacman -Rcc evolution evolution-data-server gnome-{boxes,extra,software} --noconfirm
    sudo pacman -Syyu pacman-contrib base-devel wget git vim p7zip unrar --needed --noconfirm
    sudo pacman -S arch-install-scripts lynx squashfs-tools libisoburn --needed --noconfirm

    cd /tmp
        git clone https://aur.archlinux.org/package-query.git
        git clone https://aur.archlinux.org/yaourt.git
        cd package-query && makepkg -si --noconfirm && cd ./../yaourt && makepkg -si --noconfirm
    cd ~

    yaourt -S nvidia nvidia-utils nvidia-settings bumblebee --needed --noconfirm
    yaourt -S gnome-{mines,multi-writer,nettool,power-manager,tweaks} --needed --noconfirm
## END

## BEGIN ~ First Settings
    sudo localectl set-x11-keymap br abnt2
    echo -e "en_US.UTF-8 UTF-8" | sudo tee --append /etc/locale.gen && sudo locale-gen

    echo -e 'QT_AUTO_SCREEN_SCALE_FACTOR=0' | sudo tee --append /etc/environment
    sudo mkdir -p /etc/systemd/coredump.conf.d/
    echo -e '[Coredump]\nStorage=none' | sudo tee --append /etc/systemd/coredump.conf.d/custom.conf
    echo "SystemMaxUse=50M" | sudo tee --append /etc/systemd/journald.conf

    sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"/g' /etc/default/grub
    sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT='$grub_sec'/g' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg

    sudo sed -i 's/#Color/Color/g' /etc/pacman.conf
    sudo sed -i 's/#TotalDownload/TotalDownload/g' /etc/pacman.conf

    mkdir -p /home/$user_name/{Downloads/Torrents,Documentos/VirtualBox\ VMs}
    sudo cp -R ./icons/* /usr/share/icons/

    mkdir -p /home/$user_name/.local/share/gnome-shell/extensions/
    sudo mv /usr/share/gnome-shell/extensions/* /home/$user_name/.local/share/gnome-shell/extensions/
    sudo chown $user_name:users -R /home/$user_name/.local/share/gnome-shell/extensions/

    echo -e '\nalias se="yaourt -Ss"' | sudo tee --append ~/.bashrc
    echo -e 'alias in="yaourt -S"' | sudo tee --append ~/.bashrc
    echo -e 'alias re="yaourt -Rcc"' | sudo tee --append ~/.bashrc
    echo -e 'alias up="yaourt -Syyau"' | sudo tee --append ~/.bashrc
    echo -e 'alias cl="yaourt -Scc && yaourt -Qtd"' | sudo tee --append ~/.bashrc

    echo -e 'mouse:usb:v045ep0040:name:*:\nMOUSE_DPI=400@125' | sudo tee --append  /etc/udev/hwdb.d/71-mouse-local.hwdb
    echo -e 'Section "InputClass"\n\tIdentifier "pointer stuff"\n\tMatchIsPointer "on"\n\tOption "TransformationMatrix" "1 0 0 0 1 0 0 0 0.6"\nEndSection' | sudo tee --append /etc/X11/xorg.conf.d/99-pointer-speed.conf
    sudo udevadm hwdb --update && sudo udevadm trigger /dev/input/event0

    gsettings set org.gnome.settings-daemon.plugins.media-keys max-screencast-length 0
    sudo -u gdm dbus-launch gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true

    sudo sed -i 's/load-module module-dev/#load-module module-dev/g' /etc/pulse/default.pa
## END

## BEGIN ~ Packages    
    yaourt -S net-tools sshfs ifuse ntfs-3g neofetch gst-plugins-ugly gst-libav --noconfirm
    yaourt -S bluez bluez-libs bluez-hid2hci bluez-utils bluez-plugins bluez-tools --needed --noconfirm

    yaourt -S wd719x-firmware aic94xx-firmware bluez-firmware --needed --noconfirm
    yaourt -S opencv hdf5 python-numpy python-matplotlib python-pillow python-editdistance --noconfirm
    yaourt -S itstool meson gobject-introspection vala pamac-aur --noconfirm

    yaourt -S adapta-gtk-theme paper-icon-theme --noconfirm
    yaourt -S ttf-bitstream-vera ttf-liberation ttf-ms-fonts --needed --noconfirm

    yaourt -S cups cups-filters cups-pdf hplip-plugin --noconfirm
    yaourt -S simple-scan system-config-printer pdfshuffler --noconfirm
    yaourt -S jdk8 alacarte nautilus-share nautilus-sendto openssh keepassxc --noconfirm

    yaourt -S google-chrome chrome-gnome-shell --noconfirm
    yaourt -S firefox firefox-i18n-pt-br hunspell-pt-br --noconfirm
    yaourt -S libreoffice-fresh libreoffice-fresh-pt-br libreoffice-extension-languagetool  --noconfirm

    yaourt -S vlc transmission-gtk mellowplayer --noconfirm
    yaourt -S inkscape gimp gimp-plugin-registry audacity pitivi --noconfirm
    
    yaourt -S steam wakfu-transition aisleriot --noconfirm
    yaourt -S virtualbox virtualbox-ext-oracle --noconfirm
## END

## BEGIN ~ Devel Packages
    yaourt -S nodejs npm smartgit visual-studio-code-bin --noconfirm
    yaourt -S android-studio android-tools android-udev gradle --noconfirm

    sudo npm i -g cordova ionic @angular/cli typescript typescript-formatter
    sudo mkdir /opt/android-sdk && sudo chown $user_name:wheel -R /opt/android-sdk

    export ANDROID_HOME=/opt/android-sdk
    echo -e 'export ANDROID_HOME=/opt/android-sdk' | sudo tee --append /etc/environment
    ## $ANDROID_HOME/tools/bin/sdkmanager --licenses
## END

## BEGIN ~ Services Settings
    sudo chown $user_name:wheel -R /opt/ankama/
    
    mkdir -p /home/$user_name/.config/autostart/
    echo -e "export SAL_USE_VCLPLUGIN=gtk" | sudo tee --append /etc/profile.d/libreoffice-fresh.sh
    echo -e "[Desktop Entry]\nType=Application\nName=transmission-gtk\nExec=transmission-gtk -m" > /home/$user_name/.config/autostart/transmission-gtk.desktop

    sudo gpasswd -a $user_name vboxusers
    sudo gpasswd -a $user_name bumblebee
    sudo gpasswd -a $user_name games

    sudo systemctl enable bumblebeed
    sudo systemctl enable org.cups.cupsd
## END

## BEGIN ~ Clear
    yaourt -Qtd
    yaourt -Scc
    echo -e "\nAll done."

    ## -- | shorcuts | --
    # print   : gnome-screenshot --interactive
    # terminal: gnome-terminal
    # monitor : gnome-system-monitor
    # xkill   : xkill
    # nautilus: nautilus --new-window %U
    # desktop : Ocultar todas as janelas normais

    ## -- | extensions | --
    # Activities Configurator
    # AlternateTab
    # Arch Linux Updates Indicator
    # Auto Move Windows
    # Bumblebee Status
    # Clipboard Indicator
    # Dash to Dock
    # Disconnect Wifi
    # Dynamic Battery
    # GSConnect
    # Impatience
    # Media Player Indicator
    # OpenWeather
    # Panel OSD
    # Removable Drive Menu
    # Refresh Wi-Fi connections
    # Sound Input & Output Device Chooser
    # Status Area Horizontal Spacing
    # Suspend Button
    # User Themes

    ## -- | extra | --
    # Java config: Parameters runtime: -Xms4096m -Xmx4096m
    # nvidia settings: optirun nvidia-settings -c :8
    # Steam (nvidia): LD_PRELOAD='/usr/lib/nvidia/libGL.so' optirun %command%
## END