#!/bin/bash 
#-----------------------------------------------------------------------------
# Run this script after your first boot with archlinux (Anywhere)
#-----------------------------------------------------------------------------

## BEGIN ~ Collecting information

    clear
    echo -e "Arch KDE ~ Install and set up some packages\n\n"

    user_name=$(whoami)
    echo "User name: $user_name"
    read -p "Seconds to grub [0]: " grub_sec
    
    read -p "Install Development Web Kit? [y]: " ionic
    read -p "Install Apache, MariaDB, PHP? [y]: " lampp
    read -p "Install JavaEE? [y]: " javaee
    dev="n"
    
    if   [ "$grub_sec" == "" ]; then
        grub_sec="0"
    fi

## END

## BEGIN ~ Updating system and packages

    sudo sed -i 's/#Color/Color/g' /etc/pacman.conf
    sudo sed -i 's/#TotalDownload/TotalDownload/g' /etc/pacman.conf
    
    sudo localectl set-x11-keymap br abnt2
    echo -e "en_US.UTF-8 UTF-8" | sudo tee --append /etc/locale.gen && sudo locale-gen
    
    sudo pacman -Syyu base-devel git wget --needed --noconfirm

    cd /tmp/
        git clone https://aur.archlinux.org/package-query.git
        cd package-query && makepkg -si --noconfirm && cd ..
  
        git clone https://aur.archlinux.org/yaourt.git
        cd yaourt && makepkg -si --noconfirm && cd ..

        git clone https://github.com/helmuthdu/dotfiles
        sudo sed -i 's/Java source/java/g' dotfiles/.nanorc
        sudo cp dotfiles/.bashrc dotfiles/.dircolors dotfiles/.dircolors_256 dotfiles/.nanorc /root/
        sudo cp dotfiles/.bashrc dotfiles/.dircolors dotfiles/.dircolors_256 dotfiles/.nanorc /home/$user_name/
    cd ~

    yaourt -S nvidia nvidia-utils nvidia-settings bumblebee mesa-demos --needed --noconfirm

        echo "SystemMaxUse=50M" | sudo tee --append /etc/systemd/journald.conf

        sudo mkdir -p /etc/systemd/coredump.conf.d/
        echo -e '[Coredump]\nStorage=none' | sudo tee --append /etc/systemd/coredump.conf.d/custom.conf

        sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 pci=noaer"/g' /etc/default/grub
        sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT='$grub_sec'/g' /etc/default/grub
        sudo grub-mkconfig -o /boot/grub/grub.cfg

        mkdir -p /home/$user_name/{Downloads/Torrents,VirtualBox\ VMs}
        sudo cp -R ./icons/* /usr/share/icons/
    
    yaourt -S plasma ark kcalc kate kdeconnect kwalletmanager kget kdegraphics-thumbnailers ffmpegthumbs partitionmanager filelight spectacle --needed --noconfirm
    
    yaourt -S kdenetwork-filesharing samba --needed --noconfirm
    
    sudo wget "https://git.samba.org/samba.git/?p=samba.git;a=blob_plain;f=examples/smb.conf.default;hb=HEAD" -O /etc/samba/smb.conf
    sudo sed -i 's/myhostname/myhostname wins /g' /etc/nsswitch.conf

    yaourt -Rcc plasma-vault discover --noconfirm
    
    yaourt -S openssh dkms net-tools sshfs ifuse ntfs-3g screenfetch zip p7zip unrar gst-plugins-good gst-plugins-ugly gst-libav --needed --noconfirm
    
    yaourt -S cups cups-filters cups-pdf pdfshuffler simple-scan print-manager --needed --noconfirm
    yaourt -S ttf-bitstream-vera ttf-liberation ttf-ms-fonts ttf-vista-fonts --needed --noconfirm
    yaourt -S firefox firefox-i18n-pt-br libreoffice-fresh libreoffice-fresh-pt-BR libreoffice-extension-vero --needed --noconfirm

    echo -e "export SAL_USE_VCLPLUGIN=gtk" | sudo tee --append /etc/profile.d/libreoffice-fresh.sh
    
    yaourt -S adapta-kde papirus-icon-theme gnome-icon-theme --noconfirm
    yaourt -S plasma5-applets-eventcalendar plasma5-applet-awesome-widgets latte-dock --noconfirm
    
        mkdir -p /home/$user_name/.local/share/awesomewidgets/configs/
        cp extra/arch_applet_awesome /home/$user_name/.local/share/awesomewidgets/configs/
    
        mkdir -p /home/$user_name/.config/latte/
        cp extra/arch.layout.latte /home/$user_name/.config/latte/
    
    yaourt -S jdk8 imagewriter hplip-plugin octopi-git --noconfirm
    yaourt -S keepassx2 gwenview okular vlc qbittorrent elisa --noconfirm
    yaourt -S kamoso gimp gimp-plugin-beautify inkscape audacity kdenlive frei0r-plugins --noconfirm
    yaourt -S kmines kpatience steam steam-native-runtime google-chrome --noconfirm
    yaourt -S virtualbox virtualbox-host-dkms virtualbox-guest-iso virtualbox-ext-oracle --noconfirm
    
## END

## BEGIN ~ Install and set up Ionic Framework and Cordova

    if   [ "$ionic" == "y" ] || [ "$ionic" == "Y" ] || [ "$ionic" == "" ]; then
        dev="y"
        yaourt -S visual-studio-code-bin android-studio android-tools android-udev gradle nodejs npm --noconfirm

        sudo npm install -g cordova ionic @angular/cli nodemon typescript typescript-formatter

        sudo mkdir -p /opt/android-sdk/tools/bin/sdkmanager
        sudo chown $user_name:wheel -R /opt/android-sdk
#         $ANDROID_HOME/tools/bin/sdkmanager --licenses

        mkdir -p ~/.config/Brackets/
    	echo -e '{\n\t "fonts.fontSize": "13px",\n\t "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",\n\t "linting.collapsed": true,\n\t "bb.beautify.hideDialog": false,\n\t "useTabChar": false,\n\t "themes.theme": "dark-theme",\n\t "highlightMatches": true,\n\t "styleActiveLine": true,\n\t "brackets-minimap.width": 140,\n\t "bb.beautify.beautifiers": { \n\t\t"tsfmt": { \n\t\t\t"command": "tsfmt" \n\t\t} \n\t},\n\t "bb.beautify.languages": {\n\t\t "css": "css",\n\t\t "ejs": "html",\n\t\t "handlebars": "html",\n\t\t "html": "html",\n\t\t "javascript": "js",\n\t\t "json": "js",\n\t\t "less": "css",\n\t\t "php": "html",\n\t\t "scss": "css",\n\t\t "svg": "html",\n\t\t "vue": "html",\n\t\t "xml": "html",\n\t\t "typescript": "tsfmt" \n\t} \n}' > /home/$user_name/.config/Brackets/brackets.json
    fi
    
## END

## BEGIN ~ Install and set up apache, mysql, php

    if   [ "$lampp" == "y" ] || [ "$lampp" == "Y" ] || [ "$lampp" == "" ]; then
        dev="y"
        yaourt -S mariadb apache phpmyadmin php php-{apache,cgi,gd,pgsql,sqlite,intl} --needed --noconfirm

        sudo mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
        sudo systemctl start mysqld
        sudo mysql_secure_installation

        sudo sed -i 's/DocumentRoot "\/srv\/http"/DocumentRoot "\/home\/'$user_name'\/Modelos\/"/g' /etc/httpd/conf/httpd.conf
        sudo sed -i 's/<Directory "\/srv\/http">/<Directory "\/home\/'$user_name'\/Modelos\/">/g' /etc/httpd/conf/httpd.conf
        echo -e 'Include conf/extra/php7_module.conf' | sudo tee --append /etc/httpd/conf/httpd.conf
        sudo sed -i 's/LoadModule mpm_event_module/#LoadModule mpm_event_module/g' /etc/httpd/conf/httpd.conf
        sudo sed -i 's/#LoadModule mpm_prefork_module/LoadModule mpm_prefork_module/g' /etc/httpd/conf/httpd.conf
        sudo sed -i 's/mod_mpm_event.so/mod_mpm_event.so\nLoadModule php7_module modules\/libphp7.so/g' /etc/httpd/conf/httpd.conf
        sudo sed -i 's/display_errors = Off/display_errors = On/g' /etc/php/php.ini
        sudo sed -i 's/extension=zip.so/extension=mysqli.so\nextension=mcrypt.so\nextension=pdo_mysql.so\nextension=bz2.so\nextension=zip.so\nextension=iconv.so/g' /etc/php/php.ini

        sudo sed -i 's/User http/User '$user_name'/g' /etc/httpd/conf/httpd.conf

        echo -e 'Include conf/extra/phpmyadmin.conf' | sudo tee --append /etc/httpd/conf/httpd.conf
        echo -e 'Alias /phpmyadmin "/usr/share/webapps/phpMyAdmin"\n<Directory "/usr/share/webapps/phpMyAdmin">\n\tDirectoryIndex index.php\n\tAllowOverride All\n\tOptions FollowSymlinks\n\tRequire all granted\n</Directory>' | sudo tee --append /etc/httpd/conf/extra/phpmyadmin.conf
    fi

## END

## BEGIN ~ Install java ee

    if   [ "$javaee" == "y" ] || [ "$javaee" == "Y" ] || [ "$javaee" == "" ]; then
        dev="y"
        yaourt -S netbeans tomcat8 --noconfirm

        sudo gpasswd --add $user_name tomcat8
        sudo chown root:tomcat8 -R /usr/share/tomcat8/
        sudo sed -i 's/<\/tomcat-users>/<role rolename="tomcat"\/>\n<user username="tomcat" password="123" roles="tomcat,manager-script"\/>\n<\/tomcat-users>/g' /usr/share/tomcat8/conf/tomcat-users.xml

        mkdir -p /home/$user_name/.netbeans/8.2/config/Preferences/org/netbeans/modules/
        echo -e "projectsFolder=/home/"$user_name"/Modelos/" > /home/$user_name/.netbeans/8.2/config/Preferences/org/netbeans/modules/projectui.properties
    fi

## END

## BEGIN ~ Dev

    if   [ "$dev" == "y" ]; then
        yaourt -S filezilla dbeaver smartgit --noconfirm
    fi

## END

## BEGIN ~ Configuring services

    sudo gpasswd -a $user_name vboxusers
    sudo gpasswd -a $user_name bumblebee
    sudo gpasswd -a $user_name http
    sudo gpasswd -a $user_name games
    
    sudo modprobe fuse && sudo modprobe vboxdrv
    sudo dkms autoinstall
    
    echo -e "vboxdrv\nvboxnetadp\nvboxnetflt\nvboxpci" | sudo tee --append /etc/modules-load.d/virtualbox.conf
    
    sudo systemctl enable bumblebeed
    sudo systemctl enable org.cups.cupsd
    sudo systemctl disable octopi
    
## END

## BEGIN ~ Finishing and Some tips

    yaourt -Qtd
    yaourt -Scc

    echo -e "\nAll done."

    # Event calendar: ddd, d 'de' MMM, HH:mm
    # Java config: Parameters runtime: -Xms8192m -Xmx8192m
    # nvidia settings: optirun nvidia-settings -c :8
    # Steam (nvidia): LD_PRELOAD='/usr/lib/nvidia/libGL.so' optirun %command%
        
## END
