#!/bin/bash
#--------------------------------------------------------------------
# Run this script after your first boot with archlinux (Anywhere)
#--------------------------------------------------------------------

## BEGIN ~ Collecting information
    clear && echo -e "Arch KDE ~ Install and set up some packages\n\n" 
    user_name=$(whoami) && echo "User name: $user_name"
    read -p "Seconds to grub [0]: " grub_sec

    if   [ "$grub_sec" == "" ]; then
        grub_sec="0"
    fi
## END

## BEGIN ~ First Packages
    sudo pacman -Syyu pacman-contrib base-devel cmake extra-cmake-modules --needed --noconfirm
    sudo pacman -S wget git git-lfs p7zip unrar zip ntfs-3g --needed --noconfirm

    sudo pacman -S nvidia nvidia-utils nvidia-settings bumblebee tlp --needed --noconfirm
    sudo pacman -S bluez-hid2hci bluez-utils bluez-plugins bluez-tools --needed --noconfirm

    sudo pacman -S plasma latte-dock kdeconnect kate kcalc kwalletmanager kdenlive kamoso --needed --noconfirm
    sudo pacman -S ark packagekit-qt5 ffmpegthumbs kdegraphics-thumbnailers kmines kpatience --needed --noconfirm
    sudo pacman -S okular gwenview filelight simplescreenrecorder partitionmanager --needed --noconfirm
    sudo pacman -S openssh sshfs net-tools kdenetwork-filesharing neofetch spectacle --needed --noconfirm
    sudo pacman -S print-manager simple-scan pdfarranger cups cups-filters cups-pdf --needed --noconfirm

    cd /tmp && git clone https://aur.archlinux.org/pikaur.git && cd pikaur && makepkg -fsri && cd ~
## END

## BEGIN ~ First Settings
    sudo localectl set-x11-keymap br abnt2
    echo -e "en_US.UTF-8 UTF-8" | sudo tee --append /etc/locale.gen && sudo locale-gen

    sudo mkdir -p /etc/systemd/coredump.conf.d/
    echo -e '[Coredump]\nStorage=none' | sudo tee --append /etc/systemd/coredump.conf.d/custom.conf
    echo "SystemMaxUse=50M" | sudo tee --append /etc/systemd/journald.conf

    sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"/g' /etc/default/grub
    sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT='$grub_sec'/g' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg

    sudo sed -i 's/#Color/Color/g' /etc/pacman.conf
    sudo sed -i 's/#TotalDownload/TotalDownload/g' /etc/pacman.conf

    mkdir -p /home/$user_name/{Downloads/Torrents,Documentos/VirtualBox\ VMs}
    sudo cp -R ./icons/* /usr/share/icons/

    echo -e '
    pkgin(){ pikaur -S $@; }
    pkgre(){ pikaur -Rcc $@; }
    pkgse(){ pikaur -Ss $@; }
    pkgup(){ pikaur -Syyu; }
    pkgcl(){ pikaur -Scc; orphan=$(pikaur -Qtdq) && pikaur -Rns $orphan; }
    ' | sudo tee --append ~/.bashrc

    echo -e '[ModifierOnlyShortcuts]\nMeta=org.kde.lattedock,/Latte,org.kde.LatteDock,activateLauncherMenu' | sudo tee --append ~/.config/kwinrc
    qdbus org.kde.KWin /KWin reconfigure
## END

## BEGIN ~ Packages
    pikaur -S wd719x-firmware aic94xx-firmware virtualbox virtualbox-ext-oracle--noconfirm
    pikaur -S jdk imagewriter keepassxc hplip-plugin hunspell-pt-br --noconfirm
    pikaur -S ttf-bitstream-vera ttf-liberation ttf-ms-fonts adobe-source-han-sans-otc-fonts --noconfirm
    pikaur -S google-chrome firefox firefox-i18n-pt-br --noconfirm
    pikaur -S mellowplayer vlc qbittorrent audacity gimp inkscape --noconfirm
    pikaur -S libreoffice-fresh libreoffice-fresh-pt-br libreoffice-extension-languagetool --noconfirm
## END

## BEGIN ~ Extra
    pikaur -S wakfu-transition --noconfirm
    sudo chown $user_name:wheel -R /opt/ankama/
## END

## BEGIN ~ Development Packages
    pikaur -S smartgit visual-studio-code-bin opencv --noconfirm

    pikaur -S python-{editdistance,graphviz,matplotlib,pillow,pip,pylint} --noconfirm
    pikaur -S python-{keras,scikit-learn,tensorflow-opt-cuda} --noconfirm
## END

## BEGIN ~ Widgets
    # desktop theme: nilium
    pikaur -S la-capitaine-icon-theme --noconfirm
    pikaur -S plasma5-applets-active-window-control plasma5-applet-awesome-widgets --noconfirm

    mkdir -p /home/$user_name/.local/share/awesomewidgets/configs/
    cp extra/aw-arch /home/$user_name/.local/share/awesomewidgets/configs/
## END

## BEGIN ~ Last Settings
    sudo gpasswd -a $user_name vboxusers
    sudo gpasswd -a $user_name bumblebee

    sudo systemctl enable bumblebeed
    sudo systemctl enable org.cups.cupsd
    sudo systemctl enable tlp tlp-sleep

    echo -e 'RUNTIME_PM_BLACKLIST="01:00.0"' | sudo tee --append /etc/environment

    sudo sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf
    sudo sed -i 's/sys root/sys root wheel/g' /etc/cups/cups-files.conf
## END

## BEGIN ~ Clear
    sudo pacman -Scc && sudo pacman -Rs $(pacman -Qqtd)
    echo -e "\nAll done."

    ## -- | shortcuts | --
    # terminal, monitor, dolphin, desktop, search, xkill 
    # kwin: alternar janelas presentes, mostrar grade da área de trabalho

    ## -- | extra | --
    # Java config: Parameters runtime: -Xms4096m -Xmx4096m
    # nvidia settings: optirun nvidia-settings -c :8
    # Steam (nvidia): LD_PRELOAD='/usr/lib/nvidia/libGL.so' optirun %command%
## END