#!/bin/bash
#--------------------------------------------------------------------
# Run this script after your first boot with archlinux (Anywhere)
#--------------------------------------------------------------------

## BEGIN ~ Collecting information
    clear && echo -e "Arch KDE" 
    user_name=$(whoami)
    grub_sec=0
## END

## BEGIN ~ Settings
    sudo localectl set-x11-keymap br abnt2
    echo -e "FONT=lat0-16" | sudo tee --append /etc/vconsole.conf

    sudo mkdir -p /etc/systemd/coredump.conf.d/
    echo -e "[Coredump]\nStorage=none" | sudo tee --append /etc/systemd/coredump.conf.d/custom.conf
    echo "SystemMaxUse=50M" | sudo tee --append /etc/systemd/journald.conf

    sudo sed -i "s/#AutoEnable=false/AutoEnable=true/g" /etc/bluetooth/main.conf
    sudo sed -i 's/sys root/sys root wheel/g' /etc/cups/cups-files.conf

    sudo sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=""/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3"/g' /etc/default/grub
    sudo sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT='$grub_sec'/g' /etc/default/grub
    sudo grub-mkconfig -o /boot/grub/grub.cfg

    echo -e "
    pkgin(){ pikaur -S \$@; }
    pkgre(){ pikaur -Rcc \$@; }
    pkgse(){ pikaur -Ss \$@; }
    pkgup(){ pikaur -Syyu; }
    pkgcl(){ pikaur -Scc; orphan=\$(pikaur -Qtdq) && pikaur -Rns \$orphan; }
    " | sudo tee --append ~/.bashrc
## END

## BEGIN ~ Base Packages
    sudo pacman -Syyu pacman-contrib base-devel --needed --noconfirm
    sudo pacman -S nvidia nvidia-utils nvidia-settings bumblebee --needed --noconfirm

    sudo pacman -S breeze-gtk kde-gtk-config user-manager kwalletmanager kdeplasma-addons --needed --noconfirm
    sudo pacman -S kinfocenter plasma-browser-integration kdeconnect kate kcalc kamoso --needed --noconfirm
    sudo pacman -S ark okular gwenview partitionmanager spectacle discover packagekit-qt5 --needed --noconfirm

    sudo pacman -S wget git p7zip unrar zip ffmpegthumbs neofetch --needed --noconfirm
    sudo pacman -S ntfs-3g openssh sshfs net-tools kdenetwork-filesharing --needed --noconfirm
    sudo pacman -S bluedevil bluez-hid2hci bluez-utils bluez-plugins bluez-tools --needed --noconfirm
    sudo pacman -S print-manager simple-scan pdfarranger cups cups-filters cups-pdf hplip --needed --noconfirm

    git clone https://aur.archlinux.org/pikaur.git && cd pikaur && makepkg -fsri && cd - && sudo rm -R pikaur
## END

## BEGIN ~ Packages
    pikaur -S wd719x-firmware aic94xx-firmware --noconfirm
    pikaur -S jre multibootusb keepassxc --noconfirm
    pikaur -S virtualbox virtualbox-guest-iso virtualbox-ext-oracle --noconfirm

    pikaur -S libreoffice-fresh libreoffice-fresh-pt-br --noconfirm
    pikaur -S libreoffice-extension-languagetool hunspell-en_US hunspell-pt-br --noconfirm
    pikaur -S adobe-source-han-sans-otc-fonts --noconfirm

    pikaur -S google-chrome qbittorrent gimp vlc --noconfirm
    pikaur -S latte-dock la-capitaine-icon-theme plasma5-applets-active-window-control --noconfirm
## END

## BEGIN ~ Development Packages
    pikaur -S smartgit visual-studio-code-bin --noconfirm
    pikaur -S opencv python-{matplotlib,numpy,pandas,pylint,tensorflow-opt} --noconfirm
## END

## BEGIN ~ Extra
    pikaur -S libpng12 --noconfirm
    cd ~ && wget -c https://download.wakfu.com/full/linux/x64 -O - | tar -xz 

    mkdir -p ~/.local/share/applications/
    mv Wakfu .wakfu && cd -

    echo -e "
    [Desktop Entry]
    Encoding=UTF-8
    Type=Application
    Name=Wakfu
    Icon=/home/$user_name/.wakfu/game/icon.png
    Exec=optirun /home/$user_name/.wakfu/Wakfu
    Categories=Game" | sudo tee --append ~/.local/share/applications/wakfu.desktop
## END

## BEGIN ~ Services
    sudo gpasswd -a $user_name vboxusers
    sudo gpasswd -a $user_name bumblebee

    sudo systemctl enable bumblebeed
    sudo systemctl enable org.cups.cupsd
## END

## BEGIN ~ Clear
    sudo pacman -Scc && sudo pacman -Rs $(pacman -Qqtd)
    echo -e "\nAll done."

    ## -- | shortcuts | --
    # terminal, monitor, dolphin, desktop, search, xkill 
    # kwin: alternar janelas presentes, mostrar grade da área de trabalho

    ## -- | extra | --
    # Java config: Parameters runtime: -Xms4096m -Xmx4096m
    # nvidia settings: optirun nvidia-settings -c :8
    # Steam (nvidia): LD_PRELOAD='/usr/lib/nvidia/libGL.so' optirun %command%
## END