#!/bin/bash
#-----------------------------------------------------------------------------
# Created by arthurflor mailto: arthurflor23[at]gmail[dot]com
# Run this script after your first boot with archlinux (as root)
#-----------------------------------------------------------------------------

## BEGIN ~ Collecting settings
clear
echo -e "Custom installer KDE Plasma\n"
echo -e "Permissions root and check the connection with Internet!\n"
echo -e "Language default: pt_br and hybrid graphics nvidia!\n\n"
read -p "All right? [y | n] " right
if   [ "$right" == "n" ]; then
    exit
fi

read -p "\nUsername to continue installation: " user_name
read -p "The Arch Linux is the only SO present? [y | n]  " grub_sec
## END ~ Collecting settings

## BEGIN ~ Updating system and first packages
useradd -m -G users -s /bin/bash $user_name
passwd $user_name && usermod -a -G wheel $user_name

echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
sed -i "s/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g" /etc/sudoers

echo -e "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen
localectl set-x11-keymap br abnt2
pacman -Syu yajl namcap git wget expac base-devel --needed --noconfirm

git clone https://aur.archlinux.org/cower.git && cd cower && makepkg -i && cd - 
git clone https://aur.archlinux.org/pacaur.git && cd pacaur && makepkg -i && cd -
rm -R cower/ && rm -R pacaur/

sed -i 's/#Color/Color/g' /etc/pacman.conf
git clone https://github.com/helmuthdu/dotfiles
sed -i 's/Java source/java/g' dotfiles/.nanorc
cp dotfiles/.bashrc dotfiles/.dircolors dotfiles/.dircolors_256 dotfiles/.nanorc ~/
cp dotfiles/.bashrc dotfiles/.dircolors dotfiles/.dircolors_256 dotfiles/.nanorc /home/$user_name/
rm -fr dotfiles

pacman -S xorg-server xorg-server-utils xorg-server-xwayland xorg-xinit xorg-xkill xf86-video-intel --needed --noconfirm
pacman -S xf86-input-synaptics xf86-input-mouse xf86-input-keyboard xf86-input-wacom xf86-input-libinput --needed --noconfirm
pacman -S nvidia nvidia-settings nvidia-utils lib32-nvidia-utils bumblebee primus --needed --noconfirm

pacman -S plasma breeze-kde4 kdebase-runtime kde-l10n-pt_br kdebase-kdialog kdenetwork-filesharing --needed --noconfirm
pacman -S partitionmanager ark kcalc kate kdeconnect kwalletmanager kde-meta-kdegraphics konsole --needed --noconfirm

pacman -S bash-completion pkgstats arch-wiki-lite --needed --noconfirm
pacman -S zip unzip p7zip lzop cpio nfs-utils samba smbnetfs --needed --noconfirm
pacman -S ntfs-3g dosfstools exfat-utils f2fs-tools autofs net-tools pkgfile screenfetch --needed --noconfirm
pacman -S cups cups-filters cups-pdf ghostscript gsfonts gutenprint pdfmod --needed --noconfirm
pacman -S foomatic-db foomatic-db-engine foomatic-db-nonfree foomatic-filters foomatic-db-ppds foomatic-db-nonfree-ppds hplip splix --needed --noconfirm

pacman -S aspell-pt gstreamer0.10-plugins lib32-nss sshfs ffmpegthumbs systemd-kcm cmake extra-cmake-modules dkms --needed --noconfirm
pacman -S alsa-utils xine-lib libquicktime lsdvd libstdc++5 libdvdcss mencoder transcode ifuse usbmuxd automoc4 --needed --noconfirm
pacman -S pulseaudio-alsa pulseaudio-bluetooth bluez bluez-libs bluez-utils bluez-libs bluez-firmware --needed --noconfirm

pacman -S simple-scan system-config-printer print-manager filelight --needed --noconfirm
pacman -S ttf-freefont ttf-bitstream-vera ttf-dejavu ttf-liberation wqy-microhei --needed --noconfirm
pacman -S dolphin firefox firefox-i18n-pt-br flashplugin libreoffice-fresh libreoffice-fresh-pt-BR --needed --noconfirm
## END ~ Updating system and first packages

## BEGIN ~ Other packages
pacman -S lib32-freetype2 dvd+rw-tools cdrdao ffmpeg0.10 gst-plugins-good gst-libav libpng12
pacman -S vlc phonon-qt5-vlc libva-intel-driver clamav gufw k3b qbittorrent
pacman -S gimp inkscape audacity handbrake handbrake-cli soundconverter amarok converseen
pacman -S filezilla nodejs npm virtualbox virtualbox-guest-iso virtualbox-host-dkms linux-headers
pacman -S kmines kpatience zsnes steam steam-native-runtime mysql-workbench blender kdenlive
## END ~ Other packages

## BEGIN ~ Installing and configuring Mysql + Apache + PHP
pacman -S mariadb --needed --noconfirm && mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
systemctl start mysqld && mysql_secure_installation

pacman -S apache php php-apache php-cgi php-gd php-mcrypt php-pgsql php-sqlite php-intl phpmyadmin

sed -i 's/DocumentRoot "\/srv\/http"/DocumentRoot "\/home\/'$user_name'\/Modelos\/www"/g' /etc/httpd/conf/httpd.conf
sed -i 's/<Directory "\/srv\/http">/<Directory "\/home\/'$user_name'\/Modelos\/www">/g' /etc/httpd/conf/httpd.conf
echo -e 'Include conf/extra/phpmyadmin.conf\nInclude conf/extra/php7_module.conf' >> /etc/httpd/conf/httpd.conf
sed -i 's/LoadModule mpm_event_module/#LoadModule mpm_event_module/g' /etc/httpd/conf/httpd.conf
sed -i 's/#LoadModule mpm_prefork_module/LoadModule mpm_prefork_module/g' /etc/httpd/conf/httpd.conf
sed -i 's/mod_mpm_event.so/mod_mpm_event.so\nLoadModule php7_module modules\/libphp7.so/g' /etc/httpd/conf/httpd.conf
sed -i 's/display_errors = Off/display_errors = On/g' /etc/php/php.ini
sed -i 's/display_startup_errors = Off/display_startup_errors = On/g' /etc/php/php.ini
sed -i 's/extension=zip.so/extension=mysqli.so\nextension=mcrypt.so\nextension=pdo_mysql.so\nextension=bz2.so\nextension=zip.so\nextension=iconv.so/g' /etc/php/php.ini

echo -e 'Alias /phpmyadmin "/usr/share/webapps/phpMyAdmin"\n<Directory "/usr/share/webapps/phpMyAdmin">\n\tDirectoryIndex index.php\n\tAllowOverride All\n\tOptions FollowSymlinks\n\tRequire all granted\n</Directory>' > /etc/httpd/conf/extra/phpmyadmin.conf
## END ~ Installing and configuring Mysql + Apache + PHP

## BEGIN ~ Second packages
chmod 1777 -R /tmp/
sudo -H -u $user_name bash -c "pacaur -S wd719x-firmware aic94xx-firmware ttf-ms-fonts ttf-vista-fonts ttf-google-fonts-git"
sudo -H -u $user_name bash -c "pacaur -S plymouth plymouth-theme-arch-charge virtualbox-ext-oracle clamtk hunspell-pt-br"
sudo -H -u $user_name bash -c "pacaur -S libreoffice-extension-vero jdk smartgit brackets rar dvdstyler google-chrome"
sudo -H -u $user_name bash -c "pacaur -S libreoffice-breeze-icons numix-circle-icon-theme-git numix-folders-git arc-kde-git"
sudo -H -u $user_name bash -c "pacaur -S intel-xdk brackets-bin multibootusb system-config-samba octopi-git downgrade"

pacman -Rns $(pacman -Qtdq) && pacman -Scc
echo -e "\nalias clean='pacaur -Scc && sudo rm -Rf /home/'$user_name'/.cache/pacaur/* && pacaur -Rns \$(pacaur -Qtdq)'" >> /home/$user_name/.bashrc
freshclam
## END ~ Second packages

## BEGIN ~ Configuring services + Default folders
gpasswd -a $user_name vboxusers 
gpasswd -a $user_name bumblebee
modprobe fuse && modprobe vboxdrv
dkms autoinstall 
echo -e "vboxdrv\nvboxnetadp\nvboxnetflt\nvboxpci" > /etc/modules-load.d/virtualbox.conf

systemctl enable bumblebeed
#systemctl enable smbd nmbd
systemctl enable smbd.socket
systemctl enable org.cups.cupsd
#systemctl enable mysqld 
#systemctl enable httpd
systemctl enable bluetooth
systemctl enable NetworkManager
systemctl enable ufw sddm && ufw enable
systemctl disable octopi
systemctl disable dhcpcd@enp7s0

ufw allow 1714:1764/udp && ufw allow 1714:1764/tcp && ufw allow CIFS
sed -i 's/Type=oneshot/Type=idle/g' /lib/systemd/system/ufw.service

mkdir -p /home/$user_name/{Desktop,Documentos,Downloads,Imagens,Modelos/www,Músicas,Público,Vídeos}
cp arch-menu.svg /usr/share/icons/arch-menu.svg
## END ~ Configuring services + Default folders

## BEGIN ~ Configuring and repairing other things
sed -i 's/function show_message/export STEAM_FRAME_FORCE_CLOSE=1\n\nfunction show_message/g' /usr/lib/steam/steam
echo -e "export SAL_USE_VCLPLUGIN=gtk" >> /etc/profile.d/libreoffice-fresh.sh

cp /etc/samba/smb.conf.default /etc/samba/smb.conf && pdbedit -a -u $user_name
sed -i 's/\[homes\]/;\[homes\]/g' /etc/samba/smb.conf
sed -i 's/comment = Home Directories/;comment = Home Directories/g' /etc/samba/smb.conf
sed -i 's/browseable = no/;browseable = no/g' /etc/samba/smb.conf
sed -i 's/writable = yes/;writable = yes/g' /etc/samba/smb.conf

sed -i 's/IgnoreLid=false/IgnoreLid=true/g' /etc/UPower/UPower.conf
echo -e "HandleLidSwitch=ignore\nLidSwitchIgnoreInhibited=off" >> /etc/systemd/logind.conf

echo "SystemMaxUse=50M" >> /etc/systemd/journald.conf
mkdir -p /etc/systemd/coredump.conf.d/ && echo -e '[Coredump]\nStorage=none' > /etc/systemd/coredump.conf.d/custom.conf
systemctl daemon-reload

echo -e 'Section "Device"\n\tIdentifier "Intel Graphics"\n\tDriver "intel"\n\tOption "DRI" "3"\nEndSection' > /etc/X11/xorg.conf.d/20-intel.conf
#sed -i 's/Section "Device"/Section "Device"\n    Option\t"RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x1; PowerMizerDefault=0x1; PowerMizerDefaultAC=0x1"/g' /etc/bumblebee/xorg.conf.nvidia

sed -i 's/HOOKS="base udev/HOOKS="base udev plymouth/g' /etc/mkinitcpio.conf
sed -i 's/encrypt /plymouth-encrypt /g' /etc/mkinitcpio.conf
sed -i 's/MODULES=""/MODULES="intel_agp i915"/g' /etc/mkinitcpio.conf
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 splash /g' /etc/default/grub

grub-mkconfig -o /boot/grub/grub.cfg
plymouth-set-default-theme -R arch-charge
if   [ "$grub_sec" == "y" ]; then
	sed -i 's/timeout=5/timeout=0/g' /boot/grub/grub.cfg
fi
## END ~ Configuring and repairing other things

## BEGIN ~ Finishing and Some tips
chown -R $user_name:users /home/$user_name
chmod 755 -R /home/$user_name/
clear && echo "All done."

	# Nvidia settings: optirun nvidia-settings -c :8
	# Steam: LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$LIB/libxcb.so.1 /usr/$LIB/libgpg-error.so' primusrun steam-native
	# or execute: find ~/.steam/root/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" -o -name "libgpg-error.so*" \) -print -delete
	#	Steam set game launch options (nvidia): LD_PRELOAD='/usr/lib/nvidia/libGL.so' optirun %command%
	# Wakfu java config: Parameters runtime: -Xms8192m -Xmx8192m
	# Tip for gtk2 theme on breeze: go to system settings > color > options and make sure 'apply colors to non-Qt colors' is switched off
## END
